### ISSUE TITLE
[Feature] 线条新增配置支持永远在节点上边

### ISSUE THREAD

**Issue by xiamidaxia** [bytedance/flowgram.ai#412]

**Comment by xiamidaxia** [comment]
临时方案：

```less
// z-index 是根据节点数递增，所以得再大一点
.gedit-flow-activity-line {
  z-index: 1000 !important;
}
.gedit-flow-activity-line.hovered {
  z-index: 1001 !important;
}


```

```typescript
// editor-props
{
  onInit(ctx) {
        const hoverService = ctx.get(WorkflowHoverService)
        let lastHoveredLine: WorkflowLineEntity | undefined
        hoverService.onHoveredChange(() => {
          const entityHovered = hoverService.hoveredNode
          lastHoveredLine?.node.classList.remove('hovered')
          if (entityHovered instanceof WorkflowLineEntity) {
            entityHovered.node.classList.add('hovered')
            lastHoveredLine = entityHovered;
          }
        })

   }
}
```
